### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by canerd7u** [rbaskam/laravel-google-drive-backup#2]
im using **php artisan drivebackup:run** code but get error.

In FilesystemAdapter.php line 109:

  backup:2018-06-11_17-05-38.sql

In Filesystem.php line 388:

  File not found at path: backup:2018-06-11_17-05-38.sql

**Comment by rbaskam** [comment]
Apologies, I never got alerted for this. What version of Laravel are you on?

**Comment by canerd7u** [comment]
@rbaskam my laravel versiyon is 5.5.6

**Comment by rbaskam** [comment]
I have downloaded 5.5.6, installed the package and run the backup fine. My thought is the app doesn't have permission to write to the storage/app area. When the backup is created it should be added to the storage/app with the name File not found at path: backup:2018-06-11_17-05-38.sql and then sent from there to Google Drive. I would highly recommend you check folder permissions as I cant replicate this. Apologies.
