### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by brwa-ata** [rbaskam/laravel-google-drive-backup#3]
when I run `php artisan drivebackup:run` it shows an error says
'mysqldump' is not recognized as an internal or external command, operable program or batch file.

please how to fix it?

**Comment by rbaskam** [comment]
Sounds like MySQL isn’t installed correctly or your paths are wrong. Here is the exact same issue https://github.com/schickling/laravel-backup/issues/60. Or https://stackoverflow.com/questions/31354510/mysqldump-is-not-recognized-as-an-internal-or-external-command it does sound like an issue with your setup not of the package. Hope this helps.

**Comment by brwa-ata** [comment]
Than you @rbaskam
